// Résumé PDF, compiled from resume.yaml (generated by exportResume.js
// from content/resume/ in the Hugo site).
// Usage: typst compile resume.typ assets/resume.pdf

#import "@preview/cmarker:0.1.1": render

#let data = yaml("resume.yaml")

#set document(title: data.author)

#set page(
  paper: "a4",
  margin: (x: 1.7cm, y: 1.6cm),
  footer: context {
    let current = counter(page).get().first()
    let total = counter(page).final().first()
    if current > 1 [
      #align(center)[#text(8pt, fill: rgb("#999999"))[#current / #total]]
    ]
  },
)

#set text(font: "Noto Sans", size: 9.5pt, lang: "en")
#set par(justify: true, leading: 0.55em)
#set heading(numbering: none)

#let muted = rgb("#555555")
#let accent = rgb("#1a5fb4")

// ------------------------------------------------ helpers

#let rule() = block(
  height: 0.6pt,
  width: 100%,
  fill: rgb("#cccccc"),
)

#let period(job) = {
  let end = if job.end == none { "Present" } else { job.end }
  job.start + " – " + end
}

#let meta(job) = {
  let parts = ()
  if "employer" in job and job.employer != none {
    parts.push([*#job.employer*])
  }
  if "client" in job and job.client != none {
    parts.push([#job.client])
  }
  if "tools" in job and job.tools.len() > 0 {
    parts.push([#text(fill: accent)[#job.tools.join(" · ") ]])
  }
  parts.join([#h(0.45em)#text(fill: muted)[·]#h(0.45em)])
}

// ------------------------------------------------ document

#align(center)[
  #text(size: 21pt, weight: "bold", tracking: 0.02em)[#data.author]
  #v(1pt)
  #block(width: 12cm, rule())
]

#v(10pt)

#text(size: 10.5pt, weight: "bold")[About me]
#v(4pt)
#grid(
  columns: (55pt, 1fr),
  column-gutter: 12pt,
  // the site's photo lives in assets/ and is served through Hugo Pipes
  [#image("assets/picture.jpg", width: 55pt)],
  render(data.about),
)
#v(10pt)

#text(size: 10.5pt, weight: "bold")[Experience]
#v(5pt)

#for job in data.jobs [
  #block(breakable: true)[
    #grid(
      columns: (1fr, auto),
      row-gutter: 2pt,
      [
        #text(size: 10.5pt, weight: "bold")[#job.title]
        #v(1.5pt)
        #meta(job)
      ],
      [
        #text(9pt, fill: muted)[#period(job)]
      ],
    )
    #v(5pt)
    #render(job.body)
    #v(8pt)
    #rule()
    #v(8pt)
  ]
]