// Résumé PDF, compiled from resume.yaml (generated by exportResume.js
// from content/resume/ in the Hugo site).
// Usage: typst compile resume.typ assets/resume.pdf

#import "@preview/cmarker:0.1.1": render

#let data = yaml("resume.yaml")

// Text palette borrowed from the website (static/terminal.css).
#let fg = rgb("#403352")
#let accent = rgb("#6f49ab")
#let muted = rgb("#7c7192")

#let contact = "hey@guillaumebogard.dev / +33 6 19 58 32 35 / Paris, FR"

#set document(title: data.author)

#set page(
  paper: "a4",
  margin: (x: 1.7cm, y: 0.95cm),
  footer: context {
    let current = counter(page).get().first()
    let total = counter(page).final().first()
    if current > 1 [
      #align(center)[#text(8pt, fill: muted)[#current / #total]]
    ]
  },
)

#set text(font: "Noto Sans", size: 9.5pt, lang: "en", fill: fg)
#set par(justify: true, leading: 0.44em)
#set heading(numbering: none)

// ------------------------------------------------ helpers

#let rule() = block(
  height: 0.6pt,
  width: 100%,
  fill: rgb("#cccccc"),
)

// Top-level section heading (About me, Work experience, Skills).
#let section(title) = [
  #text(size: 13pt, weight: "bold", fill: accent)[#title]
  #v(1pt)
  #rule()
  #v(3pt)
]

#let period(job) = {
  let end = if job.end == none { "Present" } else { job.end }
  job.start + " – " + end
}

// Small, muted employer/client line beneath a job title.
#let meta(job) = {
  let parts = ()
  if "employer" in job and job.employer != none {
    parts.push([#text(size: 9pt, weight: "bold", fill: muted)[#job.employer]])
  }
  if "client" in job and job.client != none {
    parts.push([#text(size: 9pt, fill: muted)[#job.client]])
  }
  if "tools" in job and job.tools.len() > 0 {
    parts.push([#text(size: 9pt, fill: accent)[#job.tools.join(" · ") ]])
  }
  parts.join([#h(0.45em)#text(size: 9pt, fill: muted)[·]#h(0.45em)])
}

// ------------------------------------------------ document

#align(center)[
  #text(size: 19pt, weight: "bold", tracking: 0.02em, fill: accent)[#data.author]
  #v(-10pt)
  #text(size: 9pt, fill: muted)[#contact]
  #v(3pt)
  #block(width: 12cm, rule())
]

#v(8pt)
#grid(
  columns: (55pt, 1fr),
  column-gutter: 12pt,
  // the site's photo lives in assets/ and is served through Hugo Pipes
  [#image("assets/picture.png", width: 55pt)],
  render(data.about),
)

#section("Work experience")
#for job in data.jobs [
  #block(breakable: false)[
    #grid(
      columns: (1fr, auto),
      row-gutter: 1pt,
      [
        #text(size: 10.5pt, weight: "bold")[#job.title]
        #v(1pt)
        #meta(job)
      ],
      [
        #text(9pt, fill: muted)[#period(job)]
      ],
    )
    #v(1pt)
    #render(job.body)
    #v(4pt)
  ]
]

#section("Skills")
#render(data.skills)

#section("Education")
#render(data.education)
